image: 'golang:1.12.171.12.17'

stages:
  - test

variables:
  GO111MODULE: "on"

before_script:
  - go version
  - git --version
  - python3 --version
  - echo 'SHELL:' "$SHELL"
  - echo 'PWD:' "$PWD"
  - echo 'CI_PROJECT_DIR:' "$CI_PROJECT_DIR"
  - echo 'PATH:' "$PATH"
  - echo 'GOPATH:' "$GOPATH"
  - cd "$CI_PROJECT_DIR/.."
  # - go install github.com/distroy/gocognit/cmd/gocognit@v1.0.6
  - bash type gocognit || go install github.com/distroy/gocognit/cmd/gocognit
  - cd "$CI_PROJECT_DIR"
  # - make setup

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $GOPATH/bin/
    - $GOPATH/pkg/github.com/
    - $GOPATH/pkg/golang.org/
    - $GOPATH/src/github.com/
    - $GOPATH/src/golang.org/

go-test:
  stage: test
  only:
    - merge_requests
  script:
    - make go-test

complexity:
  stage: test
  only:
    - merge_requests
  script:
    - echo "job:" "$CI_JOB_NAME"
    - echo "CI_MERGE_REQUEST_PROJECT_URL:" "$CI_MERGE_REQUEST_PROJECT_URL"
    - echo "CI_MERGE_REQUEST_SOURCE_PROJECT_URL:" "$CI_MERGE_REQUEST_SOURCE_PROJECT_URL"
    - cd "$CI_PROJECT_DIR/.."
    - rm -rf "$CI_PROJECT_DIR"
    - git clone "$CI_MERGE_REQUEST_PROJECT_URL" "$(basename "$CI_PROJECT_DIR")"
    - cd "$CI_PROJECT_DIR/."
    - git checkout "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - git checkout "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    # - echo "CI_MERGE_REQUEST_TARGET_BRANCH_SHA:" "$CI_MERGE_REQUEST_TARGET_BRANCH_SHA"
    # - echo "CI_MERGE_REQUEST_TARGET_BRANCH_NAME:" "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    # - echo "CI_MERGE_REQUEST_SOURCE_BRANCH_SHA:" "$CI_MERGE_REQUEST_SOURCE_BRANCH_SHA"
    # - echo "CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:" "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - python3 "$CI_PROJECT_DIR/script/complexity/git-diff-complexity" -c 15 "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" || exit 1
