name: go

on:
  push:
    branches:
      - master
      - release**
  pull_request:
    branches:
      - master
      - release**

env:
  GO111MODULE: on
  TZ: Asia/Shanghai
  WORKSPACE: "${{ github.workspace }}"

jobs:
  go-format-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.12.17"
      - run: make setup
      - run: |
          git-diff-go-format -mode all --func-input-num 4 -func-context-error-match=0

  go-cognitive-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        # name: go-setup
        with:
          go-version: "1.12.17"
      - run: make setup
      - run: |
          go-cognitive -over 15 .
          go-cognitive -top 10 .

  go-test-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.12.17"
      - run: go mod download
      - run: make go-test

  go-test-coverage-job:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.12.17"
      - run: go mod download
      - run: make setup
      - run: make go-test-coverage
      - run: git-diff-go-coverage -mode all -rate 0.5 -file log/coverage.out
