name: go

on:
  push:
    branches:
      - master
      - release**
  pull_request:
    branches:
      - master
      - release**

env:
  GO111MODULE: on
  TZ: Asia/Shanghai
  WORKSPACE: "${{ github.workspace }}"

jobs:
  go-format-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.14.15"
      - run: make setup
      - run: |
          git-diff-go-format

  go-cognitive-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        # name: go-setup
        with:
          go-version: "1.14.15"
      - run: make setup
      - run: |
          git-diff-go-cognitive

  go-test-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.14.15"
      - run: go mod download
      - run: make go-test

  go-test-coverage-job:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.14.15"
      - run: go mod download
      - run: make setup
      - run: make go-test-coverage
      - run: git-diff-go-coverage -file log/go-coverage.out
